
// Generated Oct 31, 2019 8:08:15 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Baithi generated by hbm2java
 */
@Entity
@Table(name="th"
    ,schema="dbo"
    ,catalog="thi"
)
public class Baithi  implements java.io.Serializable {


     private int id;
     private String pin;
     private double balance;
     private String expiryString;
     private String description;

    public Baithi() {
    }

    public Baithi(int id, String pin, double balance, String expiryString, String description) {
       this.id = id;
       this.pin = pin;
       this.balance = balance;
       this.expiryString = expiryString;
       this.description = description;
    }
   
     @Id 
     
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="Id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="Pin", nullable=false)
    public String getPin() {
        return this.pin;
    }
    
    public void setPin(String pin) {
        this.pin = pin;
    }

    
    @Column(name="Balance", nullable=false, precision=53, scale=0)
    public double getBalance() {
        return this.balance;
    }
    
    public void setBalance(double balance) {
        this.balance = balance;
    }

    
    @Column(name="ExpiryString", nullable=false, length=10)
    public String getExpiryString() {
        return this.expiryString;
    }
    
    public void setExpiryString(String expiryString) {
        this.expiryString = expiryString;
    }

    
    @Column(name="Description", nullable=false)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


