package edu.poly.entities;
// Generated Oct 24, 2019 1:32:50 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name="Products"
    ,schema="dbo"
    ,catalog="DemoDB"
)
public class Product  implements java.io.Serializable {


     private int productId;
     private Category categories;
     private String name;
     private int quantity;
     private double price;
     private String status;
     private String manufacturedDate;
     private String description;
     private String image;

    public Product() {
    }

	
    public Product(int productId, Category categories, String name, int quantity, double price) {
        this.productId = productId;
        this.categories = categories;
        this.name = name;
        this.quantity = quantity;
        this.price = price;
    }
    public Product(int productId, Category category, String name, int quantity, double price, String status, String manufacturedDate, String description, String image) {
       this.productId = productId;
       this.categories = category;
       this.name = name;
       this.quantity = quantity;
       this.price = price;
       this.status = status;
       this.manufacturedDate = manufacturedDate;
       this.description = description;
       this.image = image;
    }
   
     @Id 

    
    @Column(name="ProductId", unique=true, nullable=false)
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CategoryId", nullable=false)
    public Category getCategories() {
        return this.categories;
    }
    
    public void setCategories(Category categories) {
        this.categories = categories;
    }

    
    @Column(name="Name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="Quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="Price", nullable=false, precision=53, scale=0)
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }

    
    @Column(name="Status")
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="ManufacturedDate")
    public String getManufacturedDate() {
        return this.manufacturedDate;
    }
    
    public void setManufacturedDate(String manufacturedDate) {
        this.manufacturedDate = manufacturedDate;
    }

    
    @Column(name="Description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="Image")
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }




}


